src/Entity/UserParameters.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserParametersRepository;

#[ORM\Entity(repositoryClass: UserParametersRepository::class)]
class UserParameters
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'userParameters', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    #[ORM\Column(nullable: true)]
    private ?bool $darkmode = null;

    #[ORM\Column(nullable: true)]
    private ?bool $grid_show = null;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_1_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_1_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_2_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_2_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_3_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_3_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_4_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_4_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_5_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_5_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_6_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_6_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_7_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_7_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_8_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_8_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_9_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_9_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_10_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_10_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_11_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_11_web = true;
    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_12_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_12_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_13_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_13_web = true;
    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_14_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_14_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_15_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_15_web = true;
    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_16_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_16_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_17_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_17_web = true;


    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_18_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_18_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_19_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_19_web = true;

    // 

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_20_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_20_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_21_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_21_web = true;


    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_22_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_22_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_23_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_23_web = true;
    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_24_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_24_web = true;
    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_25_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_25_mail = true;
    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_26_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_26_mail = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_27_web = true;

    #[ORM\Column(nullable: true, options: ['default' => true])]
    private ?bool $notif_27_mail = true;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function isDarkmode(): ?bool
    {
        return $this->darkmode;
    }

    public function setDarkmode(?bool $darkmode): self
    {
        $this->darkmode = $darkmode;

        return $this;
    }

    public function isGridShow(): ?bool
    {
        return $this->grid_show;
    }

    public function setGridShow(?bool $grid_show): self
    {
        $this->grid_show = $grid_show;

        return $this;
    }

    public function isNotif1Mail(): ?bool
    {
        return $this->notif_1_mail;
    }

    public function setNotif1Mail(?bool $notif_1_mail): self
    {
        $this->notif_1_mail = $notif_1_mail;

        return $this;
    }

    public function isNotif1Web(): ?bool
    {
        return $this->notif_1_web;
    }

    public function setNotif1Web(?bool $notif_1_web): self
    {
        $this->notif_1_web = $notif_1_web;

        return $this;
    }

    public function isNotif2Mail(): ?bool
    {
        return $this->notif_2_mail;
    }

    public function setNotif2Mail(?bool $notif_2_mail): self
    {
        $this->notif_2_mail = $notif_2_mail;

        return $this;
    }

    public function isNotif2Web(): ?bool
    {
        return $this->notif_2_web;
    }

    public function setNotif2Web(?bool $notif_2_web): self
    {
        $this->notif_2_web = $notif_2_web;

        return $this;
    }

    public function isNotif3Mail(): ?bool
    {
        return $this->notif_3_mail;
    }

    public function setNotif3Mail(?bool $notif_3_mail): self
    {
        $this->notif_3_mail = $notif_3_mail;

        return $this;
    }

    public function isNotif3Web(): ?bool
    {
        return $this->notif_3_web;
    }

    public function setNotif3Web(?bool $notif_3_web): self
    {
        $this->notif_3_web = $notif_3_web;

        return $this;
    }

    public function isNotif4Mail(): ?bool
    {
        return $this->notif_4_mail;
    }

    public function setNotif4Mail(?bool $notif_4_mail): self
    {
        $this->notif_4_mail = $notif_4_mail;

        return $this;
    }

    public function isNotif4Web(): ?bool
    {
        return $this->notif_4_web;
    }

    public function setNotif4Web(?bool $notif_4_web): self
    {
        $this->notif_4_web = $notif_4_web;

        return $this;
    }

    public function isNotif5Mail(): ?bool
    {
        return $this->notif_5_mail;
    }

    public function setNotif5Mail(?bool $notif_5_mail): self
    {
        $this->notif_5_mail = $notif_5_mail;

        return $this;
    }

    public function isNotif5Web(): ?bool
    {
        return $this->notif_5_web;
    }

    public function setNotif5Web(?bool $notif_5_web): self
    {
        $this->notif_5_web = $notif_5_web;

        return $this;
    }

    public function isNotif6Mail(): ?bool
    {
        return $this->notif_6_mail;
    }

    public function setNotif6Mail(?bool $notif_6_mail): self
    {
        $this->notif_6_mail = $notif_6_mail;

        return $this;
    }

    public function isNotif6Web(): ?bool
    {
        return $this->notif_6_web;
    }

    public function setNotif6Web(?bool $notif_6_web): self
    {
        $this->notif_6_web = $notif_6_web;

        return $this;
    }

    public function isNotif7Mail(): ?bool
    {
        return $this->notif_7_mail;
    }

    public function setNotif7Mail(?bool $notif_7_mail): self
    {
        $this->notif_7_mail = $notif_7_mail;

        return $this;
    }

    public function isNotif7Web(): ?bool
    {
        return $this->notif_7_web;

src/Form/PublicationType.php
<?php

namespace App\Form;

use App\Entity\Publication;
use Doctrine\ORM\EntityRepository;
use App\Entity\PublicationCategory;
use App\Form\UserAutocompleteField;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PublicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'required' => false,
                'label' => "Quel est le titre de votre récit ?",
                // 'attr' => array(
                //     'placeholder' => 'Quel est le titre de cette histoire ?'
                // )
            ])
            ->add('summary', TextareaType::class, [
                'required' => false,
                'label' => "Pourriez-vous le résumer en quelques lignes ?",
            ])
            ->add('cover', FileType::class, [
                'mapped' => false,
                'required' => false,

            ])
            ->add('mature', CheckboxType::class, [
                'required' => false
            ])
            ->add('category', EntityType::class, [
                'placeholder' => "Choisir une catégorie",
                "class" => PublicationCategory::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.name', 'ASC');
                },
                'label' => "Dans quelle catégorie rangeriez-vous ce récit ?",
                'choice_label' => 'name',
                "required" => false
            ]);
    }
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Publication::class
        ]);
    }
}

templates/publication/add_publication_2.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PublicationController!
{% endblock %}

{% block body %}

	<div class="flex h-screen justify-center items-center ">
		<div class="xl:w-4/12 md:w-4/12 ">
			<div class="mx-auto my-0 "></div>
		</div>
	</div>

{% endblock %}

templates/publication/publication.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PublicationController!
{% endblock %}

{% block body %}

	<div class="flex h-screen justify-center items-center ">
		<div class="xl:w-4/12 md:w-4/12 ">
			<div class="mx-auto my-0 ">
				<h1>Publier un texte</h1>
				{{ form_start(form) }}

				{{ form_end(form) }}
			</div>
		</div>
	</div>

{% endblock %}

templates/publication/show_all.html.twig
{% extends 'base.html.twig' %}
{# ! INIT #}
{% set slugCat = category.slug|default('all') %}
{% set slugCatName = category.name|default('Tous les récits') %}
{% set route_params = app.request.attributes.get('_route_params') %}
{% set querySlug = route_params.slug|default('all') %}
{% set queryPage = route_params.page|default(1) %}
{% set queryOrder = route_params.order|default('desc') %}
{% set queryKeystring = route_params.keystring %}
{% set querySortby = route_params.sortby|default('published') %}
{# * Séparateur de mots clés dans l'URL & page #}
{% set separator = "—" %}
{% set separator_d = "——" %}
{% set pageAct = app.request.get('_route_params')['page'] is defined ? app.request.get('_route_params')['page'] : null %}
{% set random = random(0,999) %}
{# * GRID Session #}
{% if app.user %}
	{% if app.user.userParameters is defined and app.user.userParameters.gridShow == true %}
		{% set grid_status = "big" %}
		{% set grid_button_left = null %}
		{% set grid_button_right = "active" %}
	{% else %}
		{% set grid_status = null %}
		{% set grid_button_left = "active" %}
		{% set grid_button_right = null %}
	{% endif %}
{% else %}
	{% if app.session.get('grid') and not app.user and app.session.get('grid') == true %}
		{% set grid_status = "big" %}
		{% set grid_button_left = null %}
		{% set grid_button_right = "active" %}
	{% else %}
		{% set grid_status = null %}
		{% set grid_button_left = "active" %}
		{% set grid_button_right = null %}
	{% endif %}
{% endif %}
{# end #}
{% block title %}Récits |
	{{ slugCatName }}
	—
	{{ parent() }}
{% endblock %}
{% block metatags %}
	<link rel="canonical" href="https://scrilab.com{{ canonicalUrl }}/{{ slugCat != 'all' ? slugCat }}"/>
	<meta name="description" content="Publiez et lisez des romans, des nouvelles, de la poésie et plus encore sur notre plateforme littéraire en ligne. Rejoignez une communauté passionnée de littérature et découvrez de nouveaux talents dès aujourd'hui.">
{% endblock %}
{% block body %}
	<section class="w-full md:mt-1 flex gap-x-2 justify-center">
		{% if slugCat != "all" %}
			<span class="relative flex h-3 w-3">
				<span class="animate-ping absolute inline-flex h-full w-full rounded-full catColorDot-{{category.color}} opacity-75"></span>
				<span class="relative inline-flex rounded-full h-3 w-3 catColorDot-{{category.color}}"></span>
			</span>
		{% endif %}
		<h1 class="text-center font-serif mb-10">
			{{ slugCatName }}
		</h1>
	</section>
	<div class="flex flex-col md:flex-row w-full gap-x-10">
		{% if pubShowKw %}
			<aside class="w-full md:w-2/12 order-2 md:order-1">
				<hr class="xl:hidden mb-5 h-[0.3rem] bg-slate-400 dark:bg-slate-800 dark:border-none hidden"/>
				<h2 class="{{kwString ? "hidden " }} my-10 border-t pt-10 dark:border-t-slate-700 md:hidden text-center font-bold dark:text-slate-100">Mots-clés</h2>
				{% if kwString %}
					<p class="text-center text-md md:mt-0">
						<a target="showAllFrame" href="{{ path("app_publication_show_all_category", {slug:slugCat, page:1, order:orderSort, sortby:querySortby}) }}" class="text-slate-600 dark:text-slate-100 text-sm font-medium">
							<i class="fa-duotone fa-delete-left"></i>
							<span class="hover:underline">Réinitialiser</span>
						</a>
					</p>
					<hr class="my-2 dark:bg-slate-900 dark:border-slate-900">
				{% endif %}
				<div class="flex flex-wrap  justify-evenly flex-row">
					{% include "publication/_partials/_show_all_keywords.html.twig"  %}
				</div>
			</aside>
		{% endif %}
		<section class="w-full flex-col flex gap-y-12 md:gap-y-3 order-1 md:order-2" style="--animate-duration: 1s;">
			<div
				class="flex flex-col xl:flex-row mb-10 justify-between px-2 pr-5">
				{# ! COUNT PUBLICATIONS #}
				<h4 class="w-full md:w-2/6 text-center md:text-left mb-5 ml-2  font-light text-lg text-slate-500 dark:text-slate-300">
					{% set recount = count == 1 ? "1 récit" : count == 0 ? "Aucun récit" : count ~ " récits" %}
					{{ recount | default('Aucun récit.') }}
					{% if count == 0 and app.user %}
						<span class="hidden lg:inline">|</span>
						<span class="block md:hidden"></span>
						<a href="{{ path("app_publication_add") }}" class="text-sky-800 dark:text-sky-400 font-medium hover:underline">N'hésitez pas à publier le vôtre !</a>
					{% elseif count == 0 and not app.user %}
						<span class="hidden lg:inline">|</span>
						<span class="block md:hidden"></span>
						<button data-micromodal-trigger="popup-register" class="text-blue-800 dark:text-sky-400 hover:underline text-left">N'hésitez pas à publier le vôtre !</button>
					{% endif %}
				</h4>
				{# ! START - SORT BUTTON #}
				<div class="-mt-3 w-full md:w-auto flex flex-col md:flex-row gap-y-8 items-baseline gap-x-2">
					<button id="sortButton" data-dropdown-toggle="sortHover" class="flex justify-center items-center ring-1 bg-none  focus:ring-4 focus:outline-none font-medium w-full text-center rounded-lg text-xs lg:text-sm lg:mt-0 mt-2 px-4 py-2.5  {{ querySortby == 'pop' ? 'ring-sky-600 hover:bg-sky-50  text-sky-800 focus:ring-sky-300 dark:text-sky-500 dark:hover:text-sky-400 dark:ring-sky-400 dark:hover:bg-sky-900 dark:hover:ring-sky-500' : querySortby == 'published' ? 'ring-yellow-600 hover:bg-yellow-50  text-yellow-800 focus:ring-amber-300 dark:text-yellow-400 dark:ring-yellow-400 dark:hover:bg-yellow-900 dark:hover:text-yellow-400 dark:hover:ring-yellow-500' : querySortby == 'sheet' ? 'ring-red-600 hover:bg-red-50  text-red-800 focus:ring-amber-300 dark:text-red-400 dark:ring-red-400 dark:hover:bg-red-900 dark:hover:text-red-400 dark:hover:ring-red-500' : 'ring-green-600 hover:bg-green-50  text-green-800 focus:ring-green-300 dark:text-green-400 dark:ring-green-400 dark:hover:bg-green-900 dark:hover:text-green-400 dark:hover:ring-green-500'}}    " type="button">
						{% set popIcon = '<i class="fa-duotone fa-fire text-sky-800 dark:text-sky-500"></i> ' %}
						{% set newIcon = '<i class="fa-duotone fa-sparkles text-yellow-800 dark:text-yellow-400"></i>' %}
						{% set lastChapterIcon = '<i class="fa-duotone fa-file-plus text-red-800 dark:text-red-400"></i>' %}
						{% set challengeIcon = '<i class="fa-duotone fa-hand-holding-seedling text-green-800 dark:text-green-400"></i>' %}
						{% if querySortby == 'pop' %}
							{% set sortText = popIcon|raw ~ " &nbsp;&nbsp;Les plus populaires" %}
						{% endif %}
						{% if querySortby == 'published' %}
							{% set sortText = newIcon|raw ~ " &nbsp;&nbsp;Les nouveautés" %}
						{% endif %}
						{% if querySortby == 'sheet' %}
							{% set sortText = lastChapterIcon|raw ~ " &nbsp;&nbsp;Les derniers chapitres" %}
						{% endif %}
						{% if querySortby == 'challenge' %}
							{% set sortText = challengeIcon|raw ~ " &nbsp;&nbsp;Les réponses aux exercices" %}
						{% endif %}
						{{ sortText|raw }}
						<svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
						</svg>
					</button>
					<div id="sortHover" class="z-10 hidden bg-white divide-y divide-slate-100 rounded-lg shadow w-auto dark:bg-slate-700  ">
						{% set options = [
							{
								'text': 'Les plus populaires d\'abord',
								'order': 'desc',
								'sortby': 'pop',
								'class': 'rounded-t-lg',
								'icon': popIcon
							},
							
							{
								'text': 'Les nouveautés d\'abord',
								'order': 'desc',
								'sortby': 'published',
								'class': '',
								'icon': newIcon
							},
							{
								'text': 'Les derniers chapitres publiés',
								'order': 'desc',
								'sortby': 'sheet',
								'class': '',
								'icon': lastChapterIcon
							},
							{
								'text': 'Les réponses aux exercices',
								'order': 'desc',
								'sortby': 'challenge',
								'class': 'rounded-b-lg',
								'icon': challengeIcon
							},
							
						] %}
						<ul class="text-sm  text-slate-700 shadow-2xl rounded-lg" aria-labelledby="sortButton">
							{% for option in options %}
								{% if option.order == orderSort and option.sortby == querySortby %}
									{% if querySortby == "pop" %}
										{% set activeClass = "bg-sky-100 text-sky-800 hover:bg-sky-100 dark:bg-sky-900 dark:hover:bg-sky-900 dark:text-sky-300" %}
									{% elseif querySortby == "published" %}
										{% set activeClass = "bg-yellow-100 text-yellow-800 hover:bg-yellow-100 dark:bg-yellow-800 dark:hover:bg-yellow-800  dark:text-yellow-400" %}
									{% elseif querySortby == "sheet" %}
										{% set activeClass = "bg-red-100 text-red-800 hover:bg-red-100 dark:bg-red-800 dark:hover:bg-red-800  dark:text-red-400" %}
									{% elseif querySortby == "challenge" %}
										{% set activeClass = "bg-green-100 text-green-800 hover:bg-green-100 dark:bg-green-800 dark:hover:bg-green-800 rounded-b-lg dark:text-green-400" %}
									{% endif %}
								{% else %}
									{% set activeClass = "hover:bg-slate-200 dark:bg-slate-700 dark:hover:bg-slate-900 dark:text-slate-300 " %}
								{% endif %}
								<li class="py-2 {{ option.class }} {{ activeClass }} ">
									<a href="{{ path("app_publication_show_all_category", {slug: slugCat, keystring: queryKeystring, page: page, order: option.order, sortby: option.sortby}) }}" class="block px-4 py-2 ">
										{{ option.icon|raw }}
										&nbsp;{{ option.text }}</a>
								</li>
							{% endfor %}
						</ul>
					</div>
					<div class="flex flex-row items-center w-full md:w-auto justify-between gap-x-2">
						<a href="{{path("app_search", {sortBy:querySortby,pubOrAuthor:"publication", orderBy:queryOrder|upper, timeShort:"on",timeMedium:"on",timeLong:"on"})}}" class="md:mt-0 mt-2">
							<div class="bg-slate-50 py-2 px-2 rounded-lg border-[1px] border-slate-200 dark:border-slate-900 cursor-pointer hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700 hover:border-slate-400" data-tippy-content="Rechercher">
								<i class="fa-light fa-folder-magnifying-glass fa-xl text-slate-700 dark:text-slate-400"></i>
							</div>
						</a>
						<div class="flex flex-row rounded-md mt-2 md:mt-0">
							{% if app.user %}
								<button aria-label="Affichage ressérré" data-tippy-content="Affichage ressérré" id="grid" type="button" class="button-grid-show-all left {{grid_button_left}} ">
									<i class="fa-regular fa-table-cells"></i>
								</button>
								<button aria-label="Affichage détaillé" data-tippy-content="Affichage large et détaillé" id="gridSmall" type="button" class="button-grid-show-all right  {{grid_button_right}}">
									<i class="fa-regular fa-table-cells-large"></i>
								</button>
							{% else %}
								<button aria-label="Affichage ressérré" data-tippy-content="Affichage ressérré" id="grid" type="button" class="button-grid-show-all left  {{grid_button_left}}">
									<i class="fa-regular fa-table-cells"></i>
								</button>
								<button aria-label="Affichage détaillé" data-tippy-content="Affichage large et détaillé" id="gridSmallSession" type="button" class="button-grid-show-all right  {{grid_button_right}}">
									<i class="fa-regular fa-table-cells-large"></i>
								</button>
							{% endif %}
						</div>

						{% if countPage > 1 %}
							<div class="flex flex-col self-start -mt-[1.25rem] xl:-mt-[1.35rem]">
								{% include "publication/_partials/_show_all_pagination.html.twig" with {'type': "top"}  %}
							</div>
						{% endif %}
					</div>
				</div>
				{# ! PAGINATION TOP #}
			</div>

			<div class="display_publications twoMax {{grid_status}} showAll" id="PublicationShowContent">
				{% for item in pubShow %}
					{% include "publication/_partials/_show_all-publication.html.twig" with {'item': item, 'sortBy':querySortby} %}
				{% endfor %}
				{% if (kwString is null and slugCat == "all") and page == 1 and count < limit %}
					{% for i in count..limit - 1 %}
						{% include "publication/_partials/_show_all-fake-publication.html.twig" %}
					{% endfor %}
				{% endif %}
			</div>
		</section>
	</div>
	<div class="pt-20 flex justify-center">
		{% if countPage > 1 %}
			{% include "publication/_partials/_show_all_pagination.html.twig" with {'type': "bottom"}  %}
		{% endif %}
	</div>
{% endblock %}