src/Entity/ForumMessage.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ForumMessageRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: ForumMessageRepository::class)]
class ForumMessage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $published_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'forumMessages')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'forumMessages')]
    private ?ForumTopic $topic = null;

    #[ORM\OneToMany(mappedBy: 'forumMessage', targetEntity: Notification::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $notifications;

    #[ORM\OneToMany(mappedBy: 'assignForumMessage', targetEntity: Notification::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $notificationAssigns;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'forumMessages')]
    private ?self $replyTo = null;

    #[ORM\OneToMany(mappedBy: 'replyTo', targetEntity: self::class, orphanRemoval: true)]
    private Collection $forumMessages;

    #[ORM\OneToMany(mappedBy: 'message', targetEntity: ForumMessageLike::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $forumMessageLikes;

    #[ORM\OneToMany(mappedBy: 'replyForum', targetEntity: Notification::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $notificationReplies;

    #[ORM\OneToMany(mappedBy: 'likeForum', targetEntity: Notification::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $notificationLikes;

    #[ORM\OneToMany(mappedBy: 'assignForumReply', targetEntity: Notification::class)]
    private Collection $notificationAssignForumMessages;

    public function __construct()
    {
        $this->notifications = new ArrayCollection();
        $this->notificationAssigns = new ArrayCollection();
        $this->forumMessages = new ArrayCollection();
        $this->forumMessageLikes = new ArrayCollection();
        $this->notificationReplies = new ArrayCollection();
        $this->notificationLikes = new ArrayCollection();
        $this->notificationAssignForumMessages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeImmutable $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTopic(): ?ForumTopic
    {
        return $this->topic;
    }

    public function setTopic(?ForumTopic $topic): self
    {
        $this->topic = $topic;

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications->add($notification);
            $notification->setForumMessage($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->removeElement($notification)) {
            // set the owning side to null (unless already changed)
            if ($notification->getForumMessage() === $this) {
                $notification->setForumMessage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotificationAssigns(): Collection
    {
        return $this->notificationAssigns;
    }

    public function addNotificationAssign(Notification $notificationAssign): self
    {
        if (!$this->notificationAssigns->contains($notificationAssign)) {
            $this->notificationAssigns->add($notificationAssign);
            $notificationAssign->setAssignForumMessage($this);
        }

        return $this;
    }

    public function removeNotificationAssign(Notification $notificationAssign): self
    {
        if ($this->notificationAssigns->removeElement($notificationAssign)) {
            // set the owning side to null (unless already changed)
            if ($notificationAssign->getAssignForumMessage() === $this) {
                $notificationAssign->setAssignForumMessage(null);
            }
        }

        return $this;
    }
    public function getReplyTo(): ?self
    {
        return $this->replyTo;
    }

    public function setReplyTo(?self $replyTo): self
    {
        $this->replyTo = $replyTo;

        return $this;
    }
    /**
     * @return Collection<int, self>
     */
    public function getForumMessages(): Collection
    {
        return $this->forumMessages;
    }

    public function addForumMessages(self $forumMessages): self
    {
        if (!$this->forumMessages->contains($forumMessages)) {
            $this->forumMessages->add($forumMessages);
            $forumMessages->setReplyTo($this);
        }

        return $this;
    }

    public function removeForumMessages(self $forumMessages): self
    {
        if ($this->forumMessages->removeElement($forumMessages)) {
            // set the owning side to null (unless already changed)
            if ($forumMessages->getReplyTo() === $this) {
                $forumMessages->setReplyTo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ForumMessageLike>
     */
    public function getForumMessageLikes(): Collection
    {
        return $this->forumMessageLikes;
    }

    public function addForumMessageLike(ForumMessageLike $forumMessageLike): self
    {
        if (!$this->forumMessageLikes->contains($forumMessageLike)) {
            $this->forumMessageLikes->add($forumMessageLike);
            $forumMessageLike->setMessage($this);
        }

        return $this;
    }

    public function removeForumMessageLike(ForumMessageLike $forumMessageLike): self
    {
        if ($this->forumMessageLikes->removeElement($forumMessageLike)) {
            // set the owning side to null (unless already changed)
            if ($forumMessageLike->getMessage() === $this) {
                $forumMessageLike->setMessage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotificationReplies(): Collection
    {
        return $this->notificationReplies;
    }

    public function addNotificationReply(Notification $notificationReply): self
    {
        if (!$this->notificationReplies->contains($notificationReply)) {
            $this->notificationReplies->add($notificationReply);
            $notificationReply->setReplyForum($this);
        }

        return $this;
    }

    public function removeNotificationReply(Notification $notificationReply): self
    {
        if ($this->notificationReplies->removeElement($notificationReply)) {
            // set the owning side to null (unless already changed)
            if ($notificationReply->getReplyForum() === $this) {
                $notificationReply->setReplyForum(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotificationLikes(): Collection
    {
        return $this->notificationLikes;
    }

    public function addNotificationLike(Notification $notificationLike): self
    {
        if (!$this->notificationLikes->contains($notificationLike)) {
            $this->notificationLikes->add($notificationLike);
            $notificationLike->setLikeForum($this);
        }

        return $this;
    }

    public function removeNotificationLike(Notification $notificationLike): self
    {
        if ($this->notificationLikes->removeElement($notificationLike)) {
            // set the owning side to null (unless already changed)
            if ($notificationLike->getLikeForum() === $this) {
                $notificationLike->setLikeForum(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotificationAssignForumMessages(): Collection
    {
        return $this->notificationAssignForumMessages;
    }

    public function addNotificationAssignForumMessage(Notification $notificationAssignForumMessage): self
    {
        if (!$this->notificationAssignForumMessages->contains($notificationAssignForumMessage)) {
            $this->notificationAssignForumMessages->add($notificationAssignForumMessage);
            $notificationAssignForumMessage->setAssignForumReply($this);
        }

        return $this;
    }

    public function removeNotificationAssignForumMessage(Notification $notificationAssignForumMessage): self
    {

src/Entity/Inbox.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\InboxRepository;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: InboxRepository::class)]
class Inbox
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'inboxes')]
    private ?User $user = null;



    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $CreatedAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $ReadAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'inboxes')]
    private ?InboxGroup $grouped = null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getReadAt(): ?\DateTimeImmutable
    {
        return $this->ReadAt;
    }

    public function setReadAt(?\DateTimeImmutable $ReadAt): self
    {
        $this->ReadAt = $ReadAt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getGrouped(): ?InboxGroup
    {
        return $this->grouped;
    }

    public function setGrouped(?InboxGroup $grouped): self
    {
        $this->grouped = $grouped;

        return $this;
    }
}

templates/components/feed_component.html.twig
<div {{ attributes }} data-poll="delay(35000)|$render" class="w-full">
	{{component("feed_content_component")}}
</div>

templates/components/feed_user_nav_component.html.twig
<div {{ attributes }} data-poll="delay(35000)|$render">
	{{component("feed_user_nav_content_component", {"userId":userId})}}
</div>

templates/components/inbox_component.html.twig
<div {{ attributes }} data-poll class="w-full gap-y-3 items-end md:pt-10 pt-20 overflow-y-auto h-[68vh] md:h-[80vh] -z-0 pr-5" id="messages-scroll">

	{% set memberAuthorize = false %}
	{% for i in app.user.inboxGroupMembers %}
		{% if i.grouped.id == this.id %}
			{% set memberAuthorize = true %}
		{% endif %}
	{% endfor %}
	{% set n = 0 %}
	{% if memberAuthorize %}
		{% if this.messages|length == 0 %}
			<p class="text-center pt-2.5 italic opacity-70 dark:text-slate-200">
				Vous entamnez une conversation avec
				{# on fait la boucle de tous les utilisateurs #}
				{% for item in this.members %}
					{% if item.user.id != app.user.id  %}
						<strong>{{item.user.nickname}}</strong>
						{% if loop.index == this.members|length - 2 %}
							et
							{% elseif loop.index < this.members|length - 2 %},
						{% endif %}
					{% endif %}
				{% endfor %}...
			</p>
		{% endif %}
		{% for item in this.messages %}
			<div class="w-full flex flex-row gap-x-2 mt-4 {{ n == this.messages|length - 1 and item.user.id == app.user.id ? " animate__animated animate__fadein animate__faster" }} {{item.user.id == app.user.id ? 'justify-end ' : 'justify-start pl-3 md:pl-0 '}}">
				{% if item.user.profilPicture %}
					<img class="h-8 w-8 rounded-full self-start {{item.user.id == app.user.id ? " order-2" : " order-1"}}" src="{{item.user.profilPicture}}"/>
				{% else %}
					<div class="min-h-[2rem] min-w-[2.15rem] rounded-full self-start {{item.user.id == app.user.id ? " order-2" : " order-1"}} flex items-center justify-center bg-slate-200 dark:bg-slate-700 text-slate-800 dark:text-slate-100">
						{{item.user.nickname|slice(0,1)|upper}}
					</div>
				{% endif %}
				<div class="flex relative flex-col items-baseline gap-y-1  {{item.user.id == app.user.id ? " order-1" : " order-2" }}">
					<a href="{{path("app_user", {username:item.user.username})}}" class=" hover:underline font-semibold text-sm  dark:text-slate-400 {{item.user.id == app.user.id ? " text-right self-end"  }}" data-turbo-frame="_top">{{item.user.nickname }}</a>
					<p
						class="p-1 px-3 flex flex-col gap-y-1 rounded-xl {{ '<em>Message supprimé</em>' in item.content ? " opacity-50"}} {{item.user.id == app.user.id ? " self-end rounded-tr-none bg-emerald-200 text-emerald-900 dark:bg-emerald-900 dark:text-emerald-100" : " self-start rounded-tl-none bg-slate-200 text-slate-800 dark:bg-slate-700 dark:text-slate-100"}} {% if " a quitté la conversation" in item.content %} inbox-leave-conversation {% endif %}">
						{# Si le message contient "USERNAME a quitté la conversation" #}
						{% if " a quitté la conversation" in item.content %}
							{# Affiche le contenu de l'item #}
							<em>
								{% if " supprimé" in item.content %}
									<i class="fa-duotone fa-user-xmark"></i>
									&nbsp;&nbsp;
									<a href="{{path("app_user", {username:item.user.username})}}" class="hover:underline" data-turbo-frame="_top">
										<strong>{{item.user.nickname}}</strong>
									</a>
									a été renvoyé(e) de la conversation par un autre membre du groupe
								{% else %}
									<i class="fa-duotone fa-left-long-to-line"></i>
									&nbsp;&nbsp;
									<a href="{{path("app_user", {username:item.user.username})}}" class="hover:underline" data-turbo-frame="_top">
										<strong>{{item.user.nickname}}</strong>
									</a>
									a quitté la conversation
								{% endif %}
							</em>
							<span class="text-[0.65rem] flex flex-row items-baseline pt-0  gap-x-1  {{item.user.id == app.user.id ? " justify-end" :" justify-start "}} opacity-60 dark:opacity-40">
								<i class="fa-regular fa-clock"></i>
								<span>{{item.createdAt|since}}</span>
							</span>
						{% elseif "<em>Message supprimé</em>" in item.content %}
							<em>Message supprimé</em>
						{% else %}
							{{item.content|smiley_to_emoji|nl2br}}
							<span class="text-[0.65rem] flex flex-row items-baseline pt-0  gap-x-1  {{item.user.id == app.user.id ? " justify-end" :" justify-start "}} opacity-60 dark:opacity-40">
								<i class="fa-regular fa-clock"></i>
								<span class="relative flex flex-row items-center gap-x-2">{{item.createdAt|since}}
									{% if app.user.id == item.user.id %}
										|&nbsp;&nbsp;
										<div class="dropdown" style="position:absolute; right:0.28rem; bottom:0.6rem">
											<button aria-label="Supprimer ce message" class="text-emerald-800 dark:text-emerald-300 text-[0.55rem]  focus:outline-none ">
												<i class="fa-solid fa-angle-down dropdown-button  " id="ddb-{{ item.id }}"></i>
											</button>
											<div id="ddm-{{ item.id }}" class=" hidden z-50 bg-white divide-y divide-gray-100 rounded-lg right-0 absolute mt-5 shadow w-56 dark:bg-slate-700 dropdown-content">
												<ul class="text-sm text-gray-700 dark:text-gray-200">
													<li>
														<a href="{{path("app_inbox_delete_message", {id:item.id, groupId:this.id})}}" class="block rounded-lg px-4 py-2 hover:bg-slate-100 text-xs dark:hover:bg-slate-600 dark:hover:text-white">
															<i class="fa-regular fa-regular fa-trash text-red-500"></i>
															&nbsp;Supprimer ce message
														</a>
													</li>
												</ul>
											</div>
										</div>
									{% endif %}
								</span>
							</span>
						{% endif %}
					</p>
				</div>
			</div>
			<div class="hidden last-message" data-time="{{item.createdAt|date("D H:m:s")}}"></div>
			{% set n = n + 1 %}
		{% endfor %}
	{% else %}
		<div class="w-full flex flex-col h-full items-center justify-center">
			<div class="flex flex-col items-center justify-center gap-y-2">
				<i class="fa-duotone fa-comment-slash text-6xl text-slate-300 dark:text-slate-700"></i>
				<p class="text-xl text-slate-300 dark:text-slate-700">Vous avez été renvoyé(e) de ce groupe</p>
			</div>
		{% endif %}
	</div>

templates/components/inbox_group_member_component.html.twig
<div class="flex -space-x-4">
	{% if app.user.profilPicture %}
		<img class="w-8 h-8 border-2 border-white rounded-full dark:border-gray-800" src="{{app.user.profilPicture}}" alt="">
	{% else %}
		<div class="w-8 h-8 border-2 border-white bg-slate-50 rounded-full dark:border-gray-800 flex items-center justify-center text-slate-800 text-sm font-bold">
			{{app.user.nickname|slice(0,1)}}
		</div>
	{% endif %}
	{% for item in this.users %}
		{% if item.user.id != app.user.id %}
			{% if item.user.profilPicture %}
				<img class="w-8 h-8 border-2 border-white rounded-full dark:border-gray-800" src="{{item.user.profilPicture}}" alt="Photo de profil de {{item.user.nickname}}">
			{% else %}
				<div class="w-8 h-8 border-2 border-white bg-slate-50 rounded-full dark:border-gray-800 flex items-center justify-center text-slate-800 text-sm font-bold">
					{{item.user.nickname|slice(0,1)}}
				</div>
			{% endif %}
		{% endif %}
	{% endfor %}
</div>

templates/components/inbox_navbar_component.html.twig
<span {{ attributes }} data-poll="delay(10000)|$render">
	{% if this.messages > 0 %}
		<i class="fa-duotone fa-envelope-dot  text-lg  py-2" aria-label="Messagerie" style="--fa-primary-color: #e71818;" id="icon-new-message"></i>
		<div id="nbrInbox" data-nbr="{{this.messages}}" class="absolute inline-flex items-center justify-center w-5 h-5 text-[0.65rem] font-bold text-white bg-rose-500 border-2 border-white rounded-full -top-[0.01rem] right-2 dark:border-gray-900">
			{{this.messages}}
		</div>
	{% else %}
		<i class="fa-duotone fa-envelope  text-lg  py-2" aria-label="Messagerie" id="icon-no-new-message"></i>
	{% endif %}
</span>

templates/components/navbar_search_component.html.twig
<div {{attributes}} class="flex flex-col gap-y-2 w-full relative">
	{% if this.users|length == 0 and this.publications|length == 0 and this.topics|length == 0 and this.challengePublications|length == 0 and this.challenges|length == 0 %}
		<div class="sticky -top-3 py-2 border-b-slate-300 dark:bg-slate-700 bg-white z-50 dark:border-b-slate-500">
			<div class="relative -mt-5">
				<div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none mb-1">
					<i class="fa-regular fa-telescope"></i>
				</div>
				<input type="search" name="query" id="search-navb" value="{{ query }}" class="input w-full dark:bg-slate-600 placeholder:dark:text-slate-300 placeholder:text-xs" placeholder="Chercher un utilisateur, un récit, une discussion, un exercice..." data-model="query">
			</div>
		</div>
	{% else %}
		<div class="border-b-[1px] sticky -top-3 py-2 border-b-slate-300 dark:bg-slate-700 bg-white z-50 dark:border-b-slate-500">
			<div class="relative mb-3 -mt-5">
				<div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none mb-1">
					<i class="fa-regular fa-telescope"></i>
				</div>
				<input type="search" name="query" value="{{ query }}" class="input w-full dark:bg-slate-900" placeholder="Utilisateur-ice, récit, sujet de discussion..." data-model="query">
			</div>
		</div>
	{% endif %}
	{% if this.users|length > 0 %}
		<div class="flex flex-col gap-y-3">
			<h5 class="text-left font-semibold">Utilisateur-ices</h5>
			<ul>
				{% for item in this.users %}
					<li class="rounded">
						<a href="{{path("app_user", {username:item.username})}}" class="flex flex-row gap-x-2 items-center justify-start px-2 rounded w-full py-2 hover:bg-slate-50 dark:hover:bg-slate-600">
							<div class=" self-baseline w-7 h-7 relative flex-shrink-0">
								{% if item.profilPicture %}
									<img class="w-full h-full object-cover rounded-full lozad myImage" src="{{item.profilPicture}}" alt="Avatar de {{item.nickname}}">
								{% else %}
									<div class="w-full h-full object-cover rounded-full bg-slate-500  cursor-default">
										<div class=" h-full flex mx-auto items-center justify-center text-xs text-slate-200">
											{{ item.nickname|slice(0,1)|upper }}
										</div>
									</div>
								{% endif %}
							</div>
							{{item.nickname}}
						</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
	{% if this.publications|length > 0 %}
		<div class="flex flex-col gap-y-3">
			<h5 class="text-left font-semibold">Récits</h5>
			<ul>
				{% for item in this.publications %}
					<li class=" rounded ">
						<a href="{{ path("app_publication_show_one", {id:item.id, slug:item.slug}) }}" class="inline-flex gap-x-2 items-start text-left justify-start px-2 rounded w-full py-2 hover:bg-slate-50 dark:hover:bg-slate-600">
							{% if item.cover %}
								<span class="inline-flex w-4 h-4 relative flex-shrink-0">
									<img class="w-full h-full object-cover rounded  myImage mt-1" src="{{item.cover}}" alt="Couverture du récit {{item.title}}">
								</span>
							{% else %}
								<span class="inline-flex w-4 h-4 relative flex-shrink-0">
									<i class="fa-solid fa-book w-full h-full object-cover mt-1 text-slate-300 dark:text-slate-500"></i>
								</span>
							{% endif %}
							<span class="flex flex-col">
								<span>{{item.title}}</span>
								<small class="opacity-50">
									{{item.user.nickname}}
								</small>
							</span>


						</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
	{% if this.topics|length > 0 %}
		<div class="flex flex-col gap-y-3">
			<h5 class="text-left font-semibold">Sujets de discussion</h5>
			<ul>
				{% for item in this.topics %}
					<li class="rounded">
						<a href="{{path("app_forum_topic_read", {slug:item.category.slug, slugTopic:item.slug, id:item.id})}}" class="flex flex-row gap-x-2 items-center justify-start px-2 rounded w-full py-2 hover:bg-slate-50 dark:hover:bg-slate-600">
							<div class=" self-baseline w-7 h-7 relative flex-shrink-0">
								<div class="w-full h-full object-cover rounded-full catColor-{{item.category.color}}  cursor-default">
									<div class=" h-full flex mx-auto items-center justify-center text-xs text-slate-200">
										<i class="fa-duotone rounded-full {{ item.category.icon }} catColorText-{{item.category.color}}"></i>
									</div>
								</div>
							</div>
							<span class="self-start text-left flex flex-col gap-y-0.5">
								{{item.title}}
								<small class="opacity-50">{{item.category.name}}

									{{item.forumMessages|length == 0 ? "" : item.forumMessages|length > 1 ? "| " ~ item.forumMessages|length ~ " réponses," : "| " ~ item.forumMessages|length ~ " réponse,"}}
									{% if item.forumMessages|length > 0 %}
										{{item.forumMessages|length == 1 ? "il y a" : "la dernière il y a" }}
										{% for itemed in item.forumMessages %}
											{% if loop.last %}
												{{itemed.publishedAt|since}}
											{% endif %}
										{% endfor %}
									{% endif %}
								</small>
							</span>
						</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
	{% if this.challenges|length > 0 %}
		<div class="flex flex-col gap-y-3">
			<h5 class="text-left font-semibold">Exercices</h5>
			<ul>
				{% for item in this.challenges %}
					<li class="rounded">
						<a href="{{path("app_challenge_read", {slug:item.slug, id:item.id})}}" class="inline-flex gap-x-2 items-start text-left justify-start px-2 rounded w-full py-2 hover:bg-slate-50 dark:hover:bg-slate-600">
							<span class="inline-flex w-4 h-4 relative flex-shrink-0">
								<i class="fa-solid fa-book w-full h-full object-cover mt-1 text-slate-300 dark:text-slate-500"></i>
							</span>
							<span class="self-start text-left flex flex-col gap-y-0.5">
								{{item.title}}
								{% if item.dateEnd %}
									{% if item.dateEnd|date("U") >= "now"|date("U") %}
										<small class="opacity-70 text-green-400">{{item.dateEnd ? "En cours, fin de l'exercice dans " ~ item.dateEnd|since}}</small>
									{% else %}
										<small class="opacity-70 text-red-400">Exercice terminé</small>
									{% endif %}
								{% else %}
									<small class="opacity-70 text-green-400">Aucune date de fin, exercice toujours en cours</small>
								{% endif %}
							</span>
						</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
	{% if this.challengePublications|length > 0 %}
		<div class="flex flex-col gap-y-3">
			<h5 class="text-left font-semibold">Réponses aux exercices</h5>
			<ul>
				{% for item in this.challengePublications %}
					<li class=" rounded ">
						<a href="{{ path("app_publication_show_one", {id:item.id, slug:item.slug}) }}" class="inline-flex gap-x-2 items-start text-left justify-start px-2 rounded w-full py-2 hover:bg-slate-50 dark:hover:bg-slate-600">
							{% if item.cover %}
								<span class="inline-flex w-4 h-4 relative flex-shrink-0">
									<img class="w-full h-full object-cover rounded  myImage mt-1" src="{{item.cover}}" alt="Couverture du récit {{item.title}}">
								</span>
							{% else %}
								<span class="inline-flex w-4 h-4 relative flex-shrink-0">
									<i class="fa-solid fa-book w-full h-full object-cover mt-1 text-slate-300 dark:text-slate-500"></i>
								</span>
							{% endif %}
							<span class="flex flex-col">
								{{item.title}}
								<small class="opacity-50">Réponse à l'exercice «
									{{item.challenge.title}}
									»
								</small>
							</span>
						</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}

</div>